package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1



/**
 * ContenirId generated by hbm2java
 */
public class ContenirId  implements java.io.Serializable {


     private String codeA;
     private String codeC;

    public ContenirId() {
    }

    public ContenirId(String codeA, String codeC) {
       this.codeA = codeA;
       this.codeC = codeC;
    }
   
    public String getCodeA() {
        return this.codeA;
    }
    
    public void setCodeA(String codeA) {
        this.codeA = codeA;
    }
    public String getCodeC() {
        return this.codeC;
    }
    
    public void setCodeC(String codeC) {
        this.codeC = codeC;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContenirId) ) return false;
		 ContenirId castOther = ( ContenirId ) other; 
         
		 return ( (this.getCodeA()==castOther.getCodeA()) || ( this.getCodeA()!=null && castOther.getCodeA()!=null && this.getCodeA().equals(castOther.getCodeA()) ) )
 && ( (this.getCodeC()==castOther.getCodeC()) || ( this.getCodeC()!=null && castOther.getCodeC()!=null && this.getCodeC().equals(castOther.getCodeC()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeA() == null ? 0 : this.getCodeA().hashCode() );
         result = 37 * result + ( getCodeC() == null ? 0 : this.getCodeC().hashCode() );
         return result;
   }   


}


