package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1



/**
 * Contenir generated by hbm2java
 */
public class Contenir  implements java.io.Serializable {


     private ContenirId id;
     private TbArticle tbArticle;
     private TbCommande tbCommande;
     private Float qte;

    public Contenir() {
    }

	
    public Contenir(ContenirId id, TbArticle tbArticle, TbCommande tbCommande) {
        this.id = id;
        this.tbArticle = tbArticle;
        this.tbCommande = tbCommande;
    }
    public Contenir(ContenirId id, TbArticle tbArticle, TbCommande tbCommande, Float qte) {
       this.id = id;
       this.tbArticle = tbArticle;
       this.tbCommande = tbCommande;
       this.qte = qte;
    }
   
    public ContenirId getId() {
        return this.id;
    }
    
    public void setId(ContenirId id) {
        this.id = id;
    }
    public TbArticle getTbArticle() {
        return this.tbArticle;
    }
    
    public void setTbArticle(TbArticle tbArticle) {
        this.tbArticle = tbArticle;
    }
    public TbCommande getTbCommande() {
        return this.tbCommande;
    }
    
    public void setTbCommande(TbCommande tbCommande) {
        this.tbCommande = tbCommande;
    }
    public Float getQte() {
        return this.qte;
    }
    
    public void setQte(Float qte) {
        this.qte = qte;
    }




}


