package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbArticle generated by hbm2java
 */
public class TbArticle  implements java.io.Serializable {


     private String codeA;
     private TbPersonne tbPersonne;
     private String libelleA;
     private String descriptionA;
     private Float qtestockA;
     private float prixhtA;
     private String photoA;
     private String label;
     private Set tbCategories = new HashSet(0);
     private Set contenirs = new HashSet(0);

    public TbArticle() {
    }

	
    public TbArticle(String codeA, float prixhtA) {
        this.codeA = codeA;
        this.prixhtA = prixhtA;
    }
    public TbArticle(String codeA, TbPersonne tbPersonne, String libelleA, String descriptionA, Float qtestockA, float prixhtA, String photoA, String label, Set tbCategories, Set contenirs) {
       this.codeA = codeA;
       this.tbPersonne = tbPersonne;
       this.libelleA = libelleA;
       this.descriptionA = descriptionA;
       this.qtestockA = qtestockA;
       this.prixhtA = prixhtA;
       this.photoA = photoA;
       this.label = label;
       this.tbCategories = tbCategories;
       this.contenirs = contenirs;
    }
   
    public String getCodeA() {
        return this.codeA;
    }
    
    public void setCodeA(String codeA) {
        this.codeA = codeA;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public String getLibelleA() {
        return this.libelleA;
    }
    
    public void setLibelleA(String libelleA) {
        this.libelleA = libelleA;
    }
    public String getDescriptionA() {
        return this.descriptionA;
    }
    
    public void setDescriptionA(String descriptionA) {
        this.descriptionA = descriptionA;
    }
    public Float getQtestockA() {
        return this.qtestockA;
    }
    
    public void setQtestockA(Float qtestockA) {
        this.qtestockA = qtestockA;
    }
    public float getPrixhtA() {
        return this.prixhtA;
    }
    
    public void setPrixhtA(float prixhtA) {
        this.prixhtA = prixhtA;
    }
    public String getPhotoA() {
        return this.photoA;
    }
    
    public void setPhotoA(String photoA) {
        this.photoA = photoA;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Set getTbCategories() {
        return this.tbCategories;
    }
    
    public void setTbCategories(Set tbCategories) {
        this.tbCategories = tbCategories;
    }
    public Set getContenirs() {
        return this.contenirs;
    }
    
    public void setContenirs(Set contenirs) {
        this.contenirs = contenirs;
    }




}


