package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCategorie generated by hbm2java
 */
public class TbCategorie  implements java.io.Serializable {


     private String codeC;
     private TbCategorie tbCategorie;
     private String libelleC;
     private Set tbArticles = new HashSet(0);
     private Set tbCategories = new HashSet(0);

    public TbCategorie() {
    }

	
    public TbCategorie(String codeC) {
        this.codeC = codeC;
    }
    public TbCategorie(String codeC, TbCategorie tbCategorie, String libelleC, Set tbArticles, Set tbCategories) {
       this.codeC = codeC;
       this.tbCategorie = tbCategorie;
       this.libelleC = libelleC;
       this.tbArticles = tbArticles;
       this.tbCategories = tbCategories;
    }
   
    public String getCodeC() {
        return this.codeC;
    }
    
    public void setCodeC(String codeC) {
        this.codeC = codeC;
    }
    public TbCategorie getTbCategorie() {
        return this.tbCategorie;
    }
    
    public void setTbCategorie(TbCategorie tbCategorie) {
        this.tbCategorie = tbCategorie;
    }
    public String getLibelleC() {
        return this.libelleC;
    }
    
    public void setLibelleC(String libelleC) {
        this.libelleC = libelleC;
    }
    public Set getTbArticles() {
        return this.tbArticles;
    }
    
    public void setTbArticles(Set tbArticles) {
        this.tbArticles = tbArticles;
    }
    public Set getTbCategories() {
        return this.tbCategories;
    }
    
    public void setTbCategories(Set tbCategories) {
        this.tbCategories = tbCategories;
    }




}


