package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbClient generated by hbm2java
 */
public class TbClient  implements java.io.Serializable {


     private String code;
     private TbPersonne tbPersonne;
     private Date dateinscription;

    public TbClient() {
    }

	
    public TbClient(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public TbClient(TbPersonne tbPersonne, Date dateinscription) {
       this.tbPersonne = tbPersonne;
       this.dateinscription = dateinscription;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public Date getDateinscription() {
        return this.dateinscription;
    }
    
    public void setDateinscription(Date dateinscription) {
        this.dateinscription = dateinscription;
    }




}


