package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCommande generated by hbm2java
 */
public class TbCommande  implements java.io.Serializable {


     private String codeC;
     private TbPersonne tbPersonne;
     private TbStatut tbStatut;
     private Date dateC;
     private Date dateretraitC;
     private Date heureretraitC;
     private Set contenirs = new HashSet(0);

    public TbCommande() {
    }

	
    public TbCommande(String codeC, Date dateC) {
        this.codeC = codeC;
        this.dateC = dateC;
    }
    public TbCommande(String codeC, TbPersonne tbPersonne, TbStatut tbStatut, Date dateC, Date dateretraitC, Date heureretraitC, Set contenirs) {
       this.codeC = codeC;
       this.tbPersonne = tbPersonne;
       this.tbStatut = tbStatut;
       this.dateC = dateC;
       this.dateretraitC = dateretraitC;
       this.heureretraitC = heureretraitC;
       this.contenirs = contenirs;
    }
   
    public String getCodeC() {
        return this.codeC;
    }
    
    public void setCodeC(String codeC) {
        this.codeC = codeC;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public TbStatut getTbStatut() {
        return this.tbStatut;
    }
    
    public void setTbStatut(TbStatut tbStatut) {
        this.tbStatut = tbStatut;
    }
    public Date getDateC() {
        return this.dateC;
    }
    
    public void setDateC(Date dateC) {
        this.dateC = dateC;
    }
    public Date getDateretraitC() {
        return this.dateretraitC;
    }
    
    public void setDateretraitC(Date dateretraitC) {
        this.dateretraitC = dateretraitC;
    }
    public Date getHeureretraitC() {
        return this.heureretraitC;
    }
    
    public void setHeureretraitC(Date heureretraitC) {
        this.heureretraitC = heureretraitC;
    }
    public Set getContenirs() {
        return this.contenirs;
    }
    
    public void setContenirs(Set contenirs) {
        this.contenirs = contenirs;
    }




}


