package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1



/**
 * TbEmploye generated by hbm2java
 */
public class TbEmploye  implements java.io.Serializable {


     private String code;
     private TbPersonne tbPersonne;

    public TbEmploye() {
    }

    public TbEmploye(TbPersonne tbPersonne) {
       this.tbPersonne = tbPersonne;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }




}


