package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPersonne generated by hbm2java
 */
public class TbPersonne  implements java.io.Serializable {


     private String code;
     private String mail;
     private String mdp;
     private String tel;
     private String nom;
     private Set tbCommandes = new HashSet(0);
     private TbProducteur tbProducteur;
     private TbEmploye tbEmploye;
     private TbClient tbClient;
     private Set tbArticles = new HashSet(0);

    public TbPersonne() {
    }

	
    public TbPersonne(String code, String mail, String mdp) {
        this.code = code;
        this.mail = mail;
        this.mdp = mdp;
    }
    public TbPersonne(String code, String mail, String mdp, String tel, String nom, Set tbCommandes, TbProducteur tbProducteur, TbEmploye tbEmploye, TbClient tbClient, Set tbArticles) {
       this.code = code;
       this.mail = mail;
       this.mdp = mdp;
       this.tel = tel;
       this.nom = nom;
       this.tbCommandes = tbCommandes;
       this.tbProducteur = tbProducteur;
       this.tbEmploye = tbEmploye;
       this.tbClient = tbClient;
       this.tbArticles = tbArticles;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getTbCommandes() {
        return this.tbCommandes;
    }
    
    public void setTbCommandes(Set tbCommandes) {
        this.tbCommandes = tbCommandes;
    }
    public TbProducteur getTbProducteur() {
        return this.tbProducteur;
    }
    
    public void setTbProducteur(TbProducteur tbProducteur) {
        this.tbProducteur = tbProducteur;
    }
    public TbEmploye getTbEmploye() {
        return this.tbEmploye;
    }
    
    public void setTbEmploye(TbEmploye tbEmploye) {
        this.tbEmploye = tbEmploye;
    }
    public TbClient getTbClient() {
        return this.tbClient;
    }
    
    public void setTbClient(TbClient tbClient) {
        this.tbClient = tbClient;
    }
    public Set getTbArticles() {
        return this.tbArticles;
    }
    
    public void setTbArticles(Set tbArticles) {
        this.tbArticles = tbArticles;
    }




}


