package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1



/**
 * TbProducteur generated by hbm2java
 */
public class TbProducteur  implements java.io.Serializable {


     private String code;
     private TbPersonne tbPersonne;
     private String photoP;
     private String raisonsocP;

    public TbProducteur() {
    }

	
    public TbProducteur(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public TbProducteur(TbPersonne tbPersonne, String photoP, String raisonsocP) {
       this.tbPersonne = tbPersonne;
       this.photoP = photoP;
       this.raisonsocP = raisonsocP;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }
    public String getPhotoP() {
        return this.photoP;
    }
    
    public void setPhotoP(String photoP) {
        this.photoP = photoP;
    }
    public String getRaisonsocP() {
        return this.raisonsocP;
    }
    
    public void setRaisonsocP(String raisonsocP) {
        this.raisonsocP = raisonsocP;
    }




}


