package greta.speedymarket.model;
// Generated 8 sept. 2016 13:41:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbStatut generated by hbm2java
 */
public class TbStatut  implements java.io.Serializable {


     private Integer idStatut;
     private String libelle;
     private Set tbCommandes = new HashSet(0);

    public TbStatut() {
    }

	
    public TbStatut(String libelle) {
        this.libelle = libelle;
    }
    public TbStatut(String libelle, Set tbCommandes) {
       this.libelle = libelle;
       this.tbCommandes = tbCommandes;
    }
   
    public Integer getIdStatut() {
        return this.idStatut;
    }
    
    public void setIdStatut(Integer idStatut) {
        this.idStatut = idStatut;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set getTbCommandes() {
        return this.tbCommandes;
    }
    
    public void setTbCommandes(Set tbCommandes) {
        this.tbCommandes = tbCommandes;
    }




}


